### ISSUE TITLE
Input del programa

### ISSUE THREAD

**Issue by sjmunoz** [cruz/iic2333-course#2]
![Screenshot from 2019-03-25 16-15-10](https://user-images.githubusercontent.com/13787476/54957958-d6eace80-4f19-11e9-8f5e-e261e72bff52.png)
Es posible que nos entreguen un Quantum y se pida abrir la versión non-preemptive como en el ultimo 
ejemplo?

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

Por favor, las dudas en el **foro oficial:** https://github.com/IIC2333/foro-2019-1/

¡Saludos!
